#!/bin/bash
# Manual push instructions for Cerebellum

echo "=========================================="
echo "Cerebellum GitHub 提交指南"
echo "=========================================="
echo ""

# Method 1: Using the token directly (if repo exists and token has rights)
echo "方法1: 使用 GitHub CLI (推荐)"
echo ""
echo "1. 安装 GitHub CLI:"
echo "   https://cli.github.com/"
echo ""
echo "2. 登录 GitHub:"
echo "   gh auth login"
echo ""
echo "3. 创建仓库 (如果不存在):"
echo "   gh repo create ChengDuBJUT/Cerebellum --public --source=. --push"
echo ""

# Method 2: Manual steps
echo "方法2: 手动创建仓库"
echo ""
echo "步骤1: 在 GitHub 创建空仓库"
echo "   访问: https://github.com/new"
echo "   仓库名: Cerebellum"
echo "   描述: Cerebellum - AI Agent Subsystem for Token Efficiency"
echo "   选择: Public"
echo ""
echo "步骤2: 在本地执行以下命令:"
echo ""
echo "   cd C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\openclaw\\extensions\\cerebellum"
echo ""
echo "   git remote remove origin 2>/dev/null || true"
echo "   git remote add origin https://github.com/ChengDuBJUT/Cerebellum.git"
echo ""
echo "步骤3: 使用 Token 推送 (替换 YOUR_TOKEN):"
echo "   git push -u origin master"
echo ""
echo "   会提示输入密码，输入你的 Personal Access Token"
echo ""

echo "=========================================="
echo "当前状态"
echo "=========================================="
echo ""
cd "C:\Users\Administrator\AppData\Roaming\npm\node_modules\openclaw\extensions\cerebellum"
echo "✓ Git 仓库已初始化"
echo "✓ 32 个文件已提交"
echo "✓ Commit: $(git log --oneline -1)"
echo ""
echo "远程仓库:"
git remote -v 2>/dev/null || echo "  (未配置)"
echo ""
echo "文件统计:"
echo "  源代码: Go files"
echo "  模型文件: 5 files (336MB)"
echo "  文档: 8 markdown files"
echo "  脚本: 4 files (sh/bat)"
echo ""
